version: '3.8'
services:
  php-apache-environment:
    build:
      context: ./containers/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80